In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Bedroom_Fan_1.csv")

In [3]:
def assign_fan_speed(temp, hum):
    # Fan Speed 0 (Off)
    if temp == 19 and 89 <= hum <= 92:
        return 0
    elif temp == 20 and 64 <= hum <= 93:
        return 1

    # Fan Speed 1-3 (Low)
    elif 22 <= temp <= 25 and 58 <= hum <= 95:
        return 1
    elif 26 <= temp <= 27 and 83 <= hum <= 95:
        return 2
    elif 28 <= temp <= 30 and 29 <= hum <= 95:
        return 3

    # Fan Speed 4-6 (Medium)
    elif 31 <= temp <= 34 and 17 <= hum <= 95:
        return 4
    elif 35 <= temp <= 37 and 55 <= hum <= 86:
        return 5
    elif 38 <= temp <= 40 and 5 <= hum <= 60:
        return 6

    # Fan Speed 7-9 (Fastest)
    elif temp > 40:
        return 7
    
    else:
        return 8  # Default for any other range not covered

# Apply the function to create the fanSpeed column
df['fanSpeed'] = df.apply(lambda row: assign_fan_speed(row['temperature'], row['humidity']), axis=1)

In [4]:
df

,S.No.,datetime,temperature,humidity,mode,speed,opTime,eSpent,eSaved,fanSpeed
0,1,01/04/2021 0:01,32,34,0,1,271,2710,3794,4
1,2,01/04/2021 0:01,32,35,0,1,271,2710,3794,4
2,3,01/04/2021 0:01,32,35,0,1,245,2450,3430,4
3,4,01/04/2021 0:02,32,35,0,1,274,2740,3836,4
4,5,01/04/2021 0:04,32,34,0,1,151,1510,2114,4
...,...,...,...,...,...,...,...,...,...,...
79379,79380,31/07/2021 9:54,32,92,0,3,61,1220,2135,4
79380,79381,31/07/2021 9:55,31,93,0,3,30,600,1050,4
79381,79382,31/07/2021 9:55,32,92,0,3,30,600,1050,4
79382,79383,31/07/2021 9:56,31,93,0,3,212,4240,7420,4
79383,79384,31/07/2021 9:59,32,93,0,3,60,1200,2100,4

In [6]:
# Save the updated DataFrame to a new CSV file with the desired name
new_file_path = 'Bedroom_fan_updated_1.csv'
df.to_csv(new_file_path, index=False)

print(f"Dataset saved to {new_file_path}")

Dataset saved to Bedroom_fan_updated_1.csv